### ISSUE TITLE
Add Epi Outcome tags to the descriptive text dropdown on the Epi data pivot visualization

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#101]
If you go to -- or create -- an Epi data pivot visualization, you can customize various features of the visualization using the update screen:
https://v2626umcth922.rtord.epa.gov/summary/data-pivot/assessment/483/chloroform-birth-defect-epi/update/

Go to the Settings tab, and then Descriptive Text Columns. Here, you can add columns to the table. The column header dropdown allows you to choose fields from the Epi data to display.

The user wants to be able to select Epi Outcome Tag data as a descriptive text column and have it shown in the table. If you want to see an example of a similar field, Animal Data Pivot already has a descriptive text field option for tags.

JIRA APPDEV-3866

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
