### ISSUE TITLE
Add Animal Endpoint results notes field to the descriptive text dropdown on the Animal data pivot visualization

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#103]
If you go to -- or create -- an Animal data pivot visualization, you can customize various features of the visualization using the update screen:
https://v2626umcth922.rtord.epa.gov/summary/data-pivot/assessment/483/chloroform-fetal-growth-crown-rump-length-animal/update/

Go to the Settings tab, and then Descriptive Text Columns. Here, you can add columns to the table. The column header dropdown allows you to choose fields from the Animal data to display.

The user wants to be able to select Results Notes data as a descriptive text column and have it shown in the table. The comments field can be found on this screen:
https://v2626umcth922.rtord.epa.gov/ani/endpoint/28089/edit/

JIRA APPDEV-3869

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
