### ISSUE TITLE
Move General Notes/Methodology on Animal Endpoint Details screen

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#104]
The user would like to move the General Notes/Methodology section to the right of this page: https://v2626umcth922.rtord.epa.gov/ani/endpoint/27840/

So it shows up underneath the plot box. Check to see if possible and how much it might mess things up first, though, and get back to me.

JIRA APPDEV-3870

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
