### ISSUE TITLE
Allow sorting on animal endpoints list by NOEL and LOEL

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#105]
Go to https://v2626umcth922.rtord.epa.gov/ani/assessment/483/endpoints/ and click on Filter Endpoints.

The user wants to have NOEL and LOEL as options under Order By. Note LOEL and NOEL are shown by default on the list.

JIRA APPDEV-3864

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
