### ISSUE TITLE
Add tags to Epi Results screen

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#106]
In the Epi Outcome update screen, there is a field where you can add "tags." It's an autocomplete field that allows you to add multiple tags, and it has an interface to delete those tags as well.
https://v2626umcth922.rtord.epa.gov/epi/outcome/100001302/update/

The client wants the same kind of tag interface for the Epi Results update screen:
https://v2626umcth922.rtord.epa.gov/epi/result/100000017/update/

The will likely involve adding tags to the results model, but I haven't dug too deeply into how the outcome tags are set up. Take a look and see if you have any questions about it, and we'll figure it out.

JIRA APPDEV-3865

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
