### ISSUE TITLE
Add more concatenation fields to epi descriptive text columns in data pivot

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#108]
There are some specially concatenated choices in the descriptive text dropdowns on the animal data pivot, such as Animal Description (With N). You can see that here:
https://v2626umcth922.rtord.epa.gov/summary/data-pivot/assessment/483/chloroform-birth-defect-epi/update/

The user wants to add some more concatenated fields to the epi data pivot.
- Concatenate reference versus exposure group name for exposure comparison column, also add one with the number of exposed cases
- Concatenate to get the exposure description
- Concatenate to get estimate and 95%CI

Exposure description might already be there. I'll take a look at this one.

JIRA APPDEV-3871

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
