### ISSUE TITLE
Need environment ID/settings flag for different HAWC installs

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#111]
Per previous conversations, different HAWC installations for different clients might need to use flags to turn certain features on and off or modify them for particular client needs. We'd like to create both a setting that indicates which client the current installation belongs to, and an example of using that setting to set feature flags in response.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
