### ISSUE TITLE
Add ability to hide modules from the public only

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#116]
Currently, modules are either on or off in assessments, but there are occasions where we'll send out links to a public assessment that is still being worked on by HAWC team members. The concern is that some of the module names might be confusing/tempting to the general public. We should investigate adding another control to Update Enabled Modules to enable particular modules for team members only.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
