### ISSUE TITLE
Enable BMD as descriptive value for endpoint-group data pivot

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#125]
BMD and BMDL are currently available as descriptive text columns in animal bioassay data pivots, but only if the pivot is set up with an export style of One row per endpoint/result. We need to enable them for One row per endpoint-group/result-group as well.

**Comment by shapiromatron** [comment]
Closing based on discussions offline; users were unable to give a specific example of how they'd use this feature. We'll close but not delete the branch should a use be specified in the future.
