### ISSUE TITLE
update license to MIT 

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/hawc#129]
After discussions with future users of HAWC and the current copyright ownership, we have decided to change the license to a more standard MIT license, with an additional notice.

1. Update license and license views on website
2. Update HAWC user model to flag acceptance of license (v1), the prior license
3. Update HAWC user model to flag acceptance of license (v2), the new license
4. Add method for users to accept new license on login.

**Comment by JoshAddington** [comment]
Closed via #130
