### ISSUE TITLE
selenium tests v3

### ISSUE THREAD

**Issue by shapiromatron** [shapiromatron/hawc#294]
Create branch `selenium-tests-v3` to write the following new tests. If you're having a hard time writing stable selectors in selenium, feel free to ping @shapiromatron and we can work together to updating existing components to add css classes to make the selectors easier to grab onto.

To setup:

```bash
# load test database
export "DJANGO_SETTINGS_MODULE=hawc.main.settings.unittest"
createdb hawc-fixture-test
manage.py load_test_db

# start both environments
manage.py runserver
npm --prefix ./frontend run start
```

Individual tests below. I added a lot of detail for things to test, but feel free to adjust as necessary to get things working, hopefully the detail helps to describe the gist of what we want to test. Basically, we just want to make sure that things render without catastrophic errors:

1. `test_literature`
    - /user/login/
        - login pm@pm.com & pw
    - /lit/assessment/2/
        - check that  > 5 .nestedTag exist in #tag
    - /lit/assessment/2/references/
        - check that if you click "Human Study (2)", two #reference_detail_div exists
    - /lit/assessment/2/references/visualization/
        - ensure svg exists and 3 .tagnode exists in svg
    - /lit/assessment/2/references/search/
        - add "Kawana" to Authors and search, assert 1 #reference_detail_div exists
    - /lit/assessment/1/tag/untagged/
        - confirm that "References", "Tags for current reference", and "Available tags" exist

2. `test_study`
    - /user/login/
        - login pm@pm.com & pw
    - /study/assessment/2/
        - confirm 4 rows exist in table tbody
    - /study/7/
        - confirm #study_details exists
        - confirm table exists in a column says Data type(s)

3. `test_bioassay`
    - /user/login/
        - login pm@pm.com & pw
    - /ani/experiment/1/
        - confirm #objContainer > table > contains "2 year bioassay" in table
        - confirm "tester" exists under Available animal groups
    - /ani/animal-group/1/
        - confirm "sprague dawley" text exists in table
        - confirm "Oral diet"  text exists in table
        - confirm "mg/kg/d" text exists
        - confirm "my outcome" test exists
    - /ani/endpoint/1/
        - ensure LOEL -> 100 mg/kg/d exists
        - ensure svg plot exists, and .d3 .dr_dots .dose_points == 3
        - ensure #dr-tbl exists and there are 4 rows in it

4. `test_rob`
    - /user/login/
        - login pm@pm.com & pw
    - /rob/assessment/1/
        - check that "example domain Domain" and "final domain Domain" headers exist
        - check that "example metric" exists
    - /rob/assessment/1/study-assignments/
        - ensure there is 1 row with Foo et al. and 4 columns
    - /rob/3/edit/
        - ensure that there are 3 .score-form

5. `test_epi`
    - /user/login/
        - login pm@pm.com & pw
    - /epi/study-population/1/
        - Ensure "Study design" and "Case series" exist
        - Ensure 1 bullet in each list of Outcome, comparison set, and exposure metric
    - /epi/exposure/1/
        - ensure "What was measured" and "Sarin" in table
    - /epi/comparison-set/1/
        - ensure exposure table exists
        - ensure 3 groups described in exposure set
    - /epi/outcome/4/
        - ensure "Name" and "partial PTSD" exist
        - ensure .nav .nav-tabs has 1 result
    - /epi/result/1/
        - ensure two tables in objContainer
            - ensure first has "Table 2" text in it
            - ensure second has 3 groups in tbody portion

6. `test_cleanup`
    - /user/login/
        - login pm@pm.com & pw
    - /assessment/1/clean-extracted-data/
        - click "1 animal bioassay endpoints"
        - click "System"
        - add "test" to "system edit' and "submit bulk edit"
        - ensure "test (1)" is now shown
        - add "N/A" to "system edit' and "submit bulk edit"
        - ensure "N/A (1)" is now shown
    - /assessment/1/clean-study-metrics/
        - press "Load responses"
        - click the checkbox beside Foo et al.
        - Change "Probably low risk of bias" to "Not reported"
        - Press Bulk modify 1 item
        - ensure "Not reported" now shown
        - click the checkbox beside Foo et al.
        - Change "Not reported" to "Probably low risk of bias"
        - Press Bulk modify 1 item
        - ensure "Probably low risk of bias" now shown

7. `test_mgmt`
    - /user/login/
        - login pm@pm.com & pw
    - /mgmt/assessment/1/
        - assert 6 svg of class .task-chart exist
    - /mgmt/assessment/1/edit/
        - assert 1 .taskStudy row exist

8. `test_heatmap_builtins`
    - /user/login/
        - login pm@pm.com & pw
    - /assessment/2/endpoints/
        - ensure that the first two columns say "Bioassay" and "Epidemiology" and the table is 3x4
    - /ani/assessment/2/heatmap-study-design/
        - ensure an svg exists with class .d3
        - ensure that 4 exp_heatmap_cell exist

9. `test_visuals`
    - /user/login/
        - login pm@pm.com & pw
    - /summary/visual/5/
        - ensure svg exists and .legend exists in svg
    - /summary/visual/4/
        - ensure svg exists and .crossview_path_group exists in svg
    - /summary/data-pivot/assessment/2/animal-bioassay-data-pivot-endpoint/
        - ensure svg exists and .x_gridliens and .y_gridlines exist
    - /summary/data-pivot/assessment/2/data-pivot-epi/
        - ensure svg exists and .x_gridliens and .y_gridlines exist
    - /summary/visual/7/
        - ensure iframe exists inside .tableauPlaceholder
    - /summary/visual/3/
        - ensure svg exists and .legend exists in svg
    - /summary/visual/6/
        - ensure svg exists and 4 .tagnode exists in svg

**Comment by Melduous** [comment]
@shapiromatron 

I've bumped into the following things that could use some more specific css that I could use to target:

5 "ensure 3 groups described in exposure set"
6 "add "test" to "system edit'" and "click the checkbox beside Foo et al."

for #6 I haven't fully navigated the path to see what other css could be useful.

**Comment by shapiromatron** [comment]
could you please open up a draft PR on this repo and @ me, and I can add the things you need to that PR?
