### ISSUE TITLE
update bootstrap to v4

### ISSUE THREAD

**Issue by bishwobhandari** [shapiromatron/hawc#321]
update bootstrap to v4 in these files. 

•	https://github.com/shapiromatron/hawc/blob/master/hawc/templates/base.html
•	https://github.com/shapiromatron/hawc/blob/master/hawc/templates/hawc/home.html
•	https://github.com/shapiromatron/hawc/tree/master/hawc/templates/registration
•	https://github.com/shapiromatron/hawc/tree/master/hawc/templates/hawc

**Comment by shapiromatron** [comment]
First pass done; subsequent work done here https://github.com/shapiromatron/hawc/projects/1
