### ISSUE TITLE
Prefiltering RoB Heatmap by Effect Subtype

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#92]
In the setup for RoB heatmap visualizations, there are options to prefilter studies by associated endpoint data, such as system or effect. The user would like to be able to prefilter by Effect Subtype as well.

Associated with JIRA APPDEV-3856.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
