### ISSUE TITLE
Add endpoint filter to study RoB assignment screen

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#93]
The user would like to be able to filter Study RoB assignments by the endpoints associated with those studies. That way they can assign the RoB forms to the correct people. Of course, you'd only be able to filter by the endpoints that have already been added in the assessment.

Associated with JIRA APPDEV-3858.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
