### ISSUE TITLE
Add effects notes to Study RoB form

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#94]
The user would like to be able to add a list of endpoint effects when reviewing the questions about endpoints in the Study RoB. They want to have an autocomplete to choose from, akin to the effects autocomplete in the animal bioassay endpoint form, and they want to add multiple effects.

Associated with APPDEV-3857, where we're going to do a mockup before developing anything.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
