### ISSUE TITLE
Put final confidence call in center of RoB donut

### ISSUE THREAD

**Issue by shanethacker** [shapiromatron/hawc#99]
RoB has a donut graph that shows the domains as slices and the metrics as smaller segments around the outer edge. IRIS wants to make the center of the donut an indicator of the final confidence metric in the Risk of Bias questionnaire. You can use the usual colors and symbols.

Associated with JIRA APPDEV-3845.

**Comment by shapiromatron** [comment]
This will be an option which users can opt-into or out-of depending on how the RoB module is setup, is that correct?

**Comment by shanethacker** [comment]
That isn't how we were doing it, but that's the kind of thing we need to consider in the future.

**Comment by shapiromatron** [comment]
Closing to reflect how issues are now tracked in separate system; can re-open if requested
